### ISSUE TITLE
Add a note to the publishing guide that testing notes are NOT put on-chain

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/dapp-publishing#103]

**Comment by creativedrewy** [comment]
Added a ticket to enable inclusion of company-private testing note details [here](https://github.com/solana-mobile/app-publishing-spec/issues/108). While the resulting notes don't get put on-chain, publishers might be version-controlling their config.yaml, and thus inadvertently sharing the private info.

**Comment by creativedrewy** [comment]
Addressed by #211

**Comment by creativedrewy** [comment]
Addressed by #211
