### ISSUE TITLE
Finalize documentation for the publishing tools

### ISSUE THREAD

**Issue by oliveeyay** [solana-mobile/dapp-publishing#130]
Write/Improve documentation for publishers

    1. It will be much needed when we open submissions to the dApp Store to the public
    2. Besides technical documentation, it would be interesting to include policies, common reasons for rejects, etc…

Gather feedback from first publishers, improve as we go

    1. Are we missing some metadata right now?
    2. Will we be missing some metadata in the future given future designs/ideas?
    3. Think about what a path to migration could look like for existing published dApps if the specs were to evolve in the future. 

 What does it mean for the GraphQL API? What does it mean for the dApp Store? etc…

**Comment by sdlaver** [comment]
Fixed by #144
