### ISSUE TITLE
Missing icon field does not fail validation step

### ISSUE THREAD

**Issue by creativedrewy** [solana-mobile/dapp-publishing#148]
Icon is required for all three of the publishing entities, thus the validation check should enforce.

**Comment by creativedrewy** [comment]
@konoart Can you tell me more about what you're seeing with problems with the icon? Validation checks appear to be working with the sample data I'm trying.

**Comment by konoart** [comment]
@creativedrewy it's about a media with `purpose` = `icon`

**Comment by creativedrewy** [comment]
@konoart can you give a little more context about what data issues you are seeing? I'm just not seeing the ability to mint NFTs without the "icon" value.

**Comment by konoart** [comment]
@creativedrewy , sure. We have a releases submitted: https://czt544ueexwyz55ohcy73l3x45uvfzaldl7llsfux2mec7l2aw2a.arweave.net/FmfecoQl7Yz3rjix_a9352lS5Asa_rXItL6YQX16BbQ
It doesn't have a `media` with `purpose` = `icon` that's why it's failing.
