### ISSUE TITLE
Check previous' versions signature for mismatch

### ISSUE THREAD

**Issue by oliveeyay** [solana-mobile/dapp-publishing#199]
When publishers submit an app update, it would be nice to compare the APK signature with the previous version to avoid a signature mismatch (which would result in the app not being updated and errors).

A signature can be retrieved from an APK using (example):
`~/Library/Android/sdk/build-tools/33.0.0/apksigner verify --print-certs --verbose app-Stub-release.apk`

**Comment by creativedrewy** [comment]
This is most likely something that should occur on the back-end. Will close here for now.
