### ISSUE TITLE
Minting publishing NFTs hangs at end of mint operatoin

### ISSUE THREAD

**Issue by creativedrewy** [solana-mobile/dapp-publishing#226]
After successfully minting each of the publisher, app & release NFTs on Windows, the CLI tooling hangs indefinitely. Users must kill the process. The NFT is minted successfully.

**Comment by ankur2136** [comment]
Happening on Linux and mac as well.

**Comment by creativedrewy** [comment]
Confirmed present with previous releases of tooling. Some utilized API has likely changed.

**Comment by creativedrewy** [comment]
This was an issue with Helius websocket connection not adhering to the websocket spec correctly. They have resolved this and this issue has gone away.
